weaviate:
    host: "localhost"
    rest_port: "8080"
    grpc_port: "50051"
openai:
    reasoning: "none" # low, medium, high
    model: "gpt-5.1"
    span_granularity: "collocation" # word, phrase, collocation, sentence, paragraph
