weaviate:
    host: "localhost"
    http_port: "9000"
    grpc_port: "50055"
openai:
    reasoning: "medium" # low, medium, high
    model: "gpt-5.1"
    span_granularity: "phrase" # word, phrase, sentence, paragraph
