topicer:
  cls: TagProposalV1
  config:
    span_granularity: "collocation"
external_service:
  cls: OpenAIService
  config:
    model: "gpt-5.1"
    reasoning: "high"

embedding_service:
  cls: DefaultEmbeddingService
  config:
    service_url: "http://localhost:9001"
    doc_endpoint: "/embed_documents"
    query_endpoint: "/embed_query"
    timeout: 30
