topicer:
  cls: TagProposalV1
  config:
    span_granularity: "collocation"
llm_service:
  cls: OpenAIService
  config:
    model: "gpt-5.1"
    reasoning: "high"
embedding_service:
  cls: DefaultEmbeddingService
  config:
    service_url: "http://localhost:8001"
    doc_endpoint: "/embed_documents"
    query_endpoint: "/embed_query"
    timeout: 30
db_connection:
  cls: WeaviateService
  config:
    host: "localhost"
    rest_port: 8080
    grpc_port: 50051
    chunks_limit: 3